### PR TITLE
Autogenerate Themes

### PR DESCRIPTION
**Pull request by ooade**
Added some few quirks. You'll need to update the docs to reflect those changes.
* Users don't need to touch the `/themes/` directory, everything should be done via the `src` directory
* `npm run build` watch for changes and build themes
* index.json has the general theme detail, any change in there will update all themes
* italic.json has detail that should only be added to `palenight-italic`, same as `operator.json`

If you create a new variant, add it to `/src` and call it in `/src/index.js` inside readFileAsync() and add it using 
```js
themify(
		data,
		variantSrc,
		buildDest,
		successMessage
	)
```

### CODE REVIEW

**Comment by ooade** [comment]
P.S: Because of my editor's prettier config, your package.json got reformatted. Don't know why that happened tho. It usually follow the file formatting buh it didn't. I'll fix that later buh you can update the format on your end before merging. Cheers!

**Comment by whizkydee** [comment]
Wow! Is this real? Thanks a lot bro! You did all this for me

**Comment by ooade** [comment]
Yeah, adding that should do and thanks for reminding me it's called `indentation`:sweat_smile: Bin trying to remember that word.

**Comment by whizkydee** [comment]
Thanks again @ooade.

**Pull request merged**
